version: '3'
services:
  db:
    container_name: db
    image: postgres:9.0
    environment:
      - POSTGRES_DB=of
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432